<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Appointment;

class AppointmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $appointments = [
            [
                'patient_id' => 1,
                'doctor_id' => 1,
                'appointment_date' => '2025-01-20',
                'appointment_time' => '10:00:00',
                'duration_minutes' => 30,
                'appointment_type' => 'Konsultasi Rutin',
                'status' => 'confirmed',
                'priority' => 'normal',
                'reason' => 'Kontrol hipertensi dan penyesuaian obat',
                'notes' => 'Pasien sudah minum obat secara teratur',
                'reminder_sent' => true,
                'reminder_time' => '2025-01-19 08:00:00',
                'check_in_time' => '2025-01-20 09:55:00',
                'start_time' => '2025-01-20 10:00:00',
                'end_time' => '2025-01-20 10:25:00',
                'outcome' => 'Kontrol rutin, tekanan darah stabil',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-20',
                'cancellation_reason' => null,
                'rescheduled_from' => null,
                'rescheduled_to' => null,
                'insurance_used' => true,
                'payment_status' => 'paid',
                'payment_amount' => 150000.00,
            ],
            [
                'patient_id' => 2,
                'doctor_id' => 2,
                'appointment_date' => '2025-01-22',
                'appointment_time' => '14:30:00',
                'duration_minutes' => 45,
                'appointment_type' => 'Konsultasi Kandungan',
                'status' => 'confirmed',
                'priority' => 'normal',
                'reason' => 'USG kehamilan trimester 1',
                'notes' => 'Kehamilan 8 minggu, perlu USG',
                'reminder_sent' => true,
                'reminder_time' => '2025-01-21 16:20:00',
                'check_in_time' => '2025-01-22 14:25:00',
                'start_time' => '2025-01-22 14:30:00',
                'end_time' => '2025-01-22 15:10:00',
                'outcome' => 'USG normal, perkembangan janin baik',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-22',
                'cancellation_reason' => null,
                'rescheduled_from' => null,
                'rescheduled_to' => null,
                'insurance_used' => true,
                'payment_status' => 'paid',
                'payment_amount' => 200000.00,
            ],
            [
                'patient_id' => 3,
                'doctor_id' => 3,
                'appointment_date' => '2025-01-18',
                'appointment_time' => '09:15:00',
                'duration_minutes' => 25,
                'appointment_type' => 'Konsultasi Anak',
                'status' => 'cancelled',
                'priority' => 'urgent',
                'reason' => 'Demam tinggi dan batuk',
                'notes' => 'Anak demam 39°C, batuk berdahak',
                'reminder_sent' => true,
                'reminder_time' => '2025-01-17 07:00:00',
                'check_in_time' => null,
                'start_time' => null,
                'end_time' => null,
                'outcome' => null,
                'follow_up_required' => false,
                'follow_up_date' => null,
                'cancellation_reason' => 'Pasien tidak bisa datang, minta reschedule',
                'rescheduled_from' => null,
                'rescheduled_to' => '2025-01-25',
                'insurance_used' => true,
                'payment_status' => 'refunded',
                'payment_amount' => 0.00,
            ],
            [
                'patient_id' => 4,
                'doctor_id' => 4,
                'appointment_date' => '2025-01-25',
                'appointment_time' => '11:00:00',
                'duration_minutes' => 40,
                'appointment_type' => 'Konsultasi Diabetes',
                'status' => 'confirmed',
                'priority' => 'normal',
                'reason' => 'Kontrol gula darah dan penyesuaian insulin',
                'notes' => 'Pasien baru diagnosis diabetes tipe 2',
                'reminder_sent' => true,
                'reminder_time' => '2025-01-24 09:00:00',
                'check_in_time' => '2025-01-25 10:50:00',
                'start_time' => '2025-01-25 11:00:00',
                'end_time' => '2025-01-25 11:35:00',
                'outcome' => 'Mulai terapi metformin, edukasi pola hidup',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-25',
                'cancellation_reason' => null,
                'rescheduled_from' => null,
                'rescheduled_to' => null,
                'insurance_used' => true,
                'payment_status' => 'paid',
                'payment_amount' => 180000.00,
            ],
            [
                'patient_id' => 5,
                'doctor_id' => 5,
                'appointment_date' => '2025-01-28',
                'appointment_time' => '08:30:00',
                'duration_minutes' => 50,
                'appointment_type' => 'Konsultasi Jantung',
                'status' => 'confirmed',
                'priority' => 'high',
                'reason' => 'Evaluasi angina pektoris',
                'notes' => 'Pasien dengan riwayat angina, perlu evaluasi',
                'reminder_sent' => true,
                'reminder_time' => '2025-01-27 06:30:00',
                'check_in_time' => '2025-01-28 08:20:00',
                'start_time' => '2025-01-28 08:30:00',
                'end_time' => '2025-01-28 09:15:00',
                'outcome' => 'Angina stabil, lanjutkan terapi, rencana angiografi',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-28',
                'cancellation_reason' => null,
                'rescheduled_from' => null,
                'rescheduled_to' => null,
                'insurance_used' => true,
                'payment_status' => 'paid',
                'payment_amount' => 250000.00,
            ],
            [
                'patient_id' => 1,
                'doctor_id' => 6,
                'appointment_date' => '2025-02-05',
                'appointment_time' => '13:00:00',
                'duration_minutes' => 20,
                'appointment_type' => 'Konsultasi Kulit',
                'status' => 'scheduled',
                'priority' => 'normal',
                'reason' => 'Follow-up dermatitis atopik',
                'notes' => 'Evaluasi respon terapi topikal',
                'reminder_sent' => false,
                'reminder_time' => null,
                'check_in_time' => null,
                'start_time' => null,
                'end_time' => null,
                'outcome' => null,
                'follow_up_required' => false,
                'follow_up_date' => null,
                'cancellation_reason' => null,
                'rescheduled_from' => null,
                'rescheduled_to' => null,
                'insurance_used' => false,
                'payment_status' => 'pending',
                'payment_amount' => 120000.00,
            ],
        ];

        foreach ($appointments as $appointment) {
            Appointment::create($appointment);
        }
    }
}
