<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Referral;

class ReferralSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $referrals = [
            [
                'patient_id' => 1,
                'doctor_id' => 1,
                'referral_number' => 'RFL00120250115',
                'referral_date' => '2025-01-15',
                'urgency_level' => 'urgent',
                'referral_type' => 'specialist_consultation',
                'referring_facility' => 'RS Sirama - Poli Penyakit Dalam',
                'receiving_facility' => 'RS Cipto Mangunkusumo - Kardiologi Intervensi',
                'receiving_doctor' => 'Dr. Spesialis Jantung Intervensi',
                'diagnosis' => 'Suspect Acute Coronary Syndrome',
                'clinical_findings' => 'Nyeri dada klasik angina, EKG ST elevasi, troponin positif',
                'investigations_done' => 'EKG, troponin, echocardiography',
                'treatment_given' => 'Aspirin, heparin, nitroglycerin, morphine',
                'reason_for_referral' => 'Perlu angiografi koroner dan PCI',
                'special_instructions' => 'Prioritas tinggi, siapkan cath lab',
                'status' => 'approved',
                'approved_by' => 5,
                'approved_date' => '2025-01-15',
                'approval_notes' => 'Disetujui untuk PCI emergency',
                'outcome' => 'Successful PCI, stent placement',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-15',
                'transportation_mode' => 'Ambulance',
                'accompanying_person' => 'Perawat ICU',
                'insurance_coverage' => true,
                'estimated_cost' => 15000000.00,
            ],
            [
                'patient_id' => 2,
                'doctor_id' => 2,
                'referral_number' => 'RFL00220250118',
                'referral_date' => '2025-01-18',
                'urgency_level' => 'emergency',
                'referral_type' => 'higher_level_care',
                'referring_facility' => 'RS Sirama - IGD',
                'receiving_facility' => 'RS Cipto Mangunkusumo - ICU',
                'receiving_doctor' => 'Dr. Spesialis ICU',
                'diagnosis' => 'Severe Pneumonia with Sepsis',
                'clinical_findings' => 'Sesak napas berat, demam 39.5°C, SpO2 85%, confusion',
                'investigations_done' => 'CXR, blood culture, ABG, lactate',
                'treatment_given' => 'IV antibiotics, oxygen, IVF, vasopressors',
                'reason_for_referral' => 'Perlu ventilasi mekanik dan critical care',
                'special_instructions' => 'Intubasi sebelum transfer, monitor vital sign',
                'status' => 'approved',
                'approved_by' => 7,
                'approved_date' => '2025-01-18',
                'approval_notes' => 'Emergency referral untuk ICU care',
                'outcome' => 'Admitted to ICU, intubated',
                'follow_up_required' => true,
                'follow_up_date' => '2025-01-25',
                'transportation_mode' => 'Ambulance with ventilator',
                'accompanying_person' => 'Dokter IGD + Perawat',
                'insurance_coverage' => true,
                'estimated_cost' => 25000000.00,
            ],
            [
                'patient_id' => 4,
                'doctor_id' => 4,
                'referral_number' => 'RFL00320250122',
                'referral_date' => '2025-01-22',
                'urgency_level' => 'normal',
                'referral_type' => 'specialist_consultation',
                'referring_facility' => 'RS Sirama - Poli Endokrin',
                'receiving_facility' => 'RSCM - Endokrinologi',
                'receiving_doctor' => 'Dr. Spesialis Endokrinologi',
                'diagnosis' => 'Diabetes Mellitus Tipe 2 uncontrolled',
                'clinical_findings' => 'Gula darah 280 mg/dL, HbA1c 9.2%, neuropathy',
                'investigations_done' => 'FBS, HbA1c, lipid profile, renal function',
                'treatment_given' => 'Insulin therapy initiated',
                'reason_for_referral' => 'Kontrol diabetes yang sulit, perlu insulin pump',
                'special_instructions' => 'Bawa semua hasil lab terbaru',
                'status' => 'pending',
                'approved_by' => null,
                'approved_date' => null,
                'approval_notes' => null,
                'outcome' => null,
                'follow_up_required' => false,
                'follow_up_date' => null,
                'transportation_mode' => 'Kendaraan pribadi',
                'accompanying_person' => 'Keluarga',
                'insurance_coverage' => true,
                'estimated_cost' => 500000.00,
            ],
            [
                'patient_id' => 5,
                'doctor_id' => 5,
                'referral_number' => 'RFL00420250125',
                'referral_date' => '2025-01-25',
                'urgency_level' => 'urgent',
                'referral_type' => 'diagnostic_procedure',
                'referring_facility' => 'RS Sirama - Poli Jantung',
                'receiving_facility' => 'RS Harapan Kita - Kardiologi',
                'receiving_doctor' => 'Dr. Spesialis Elektrofisiologi',
                'diagnosis' => 'Unstable Angina',
                'clinical_findings' => 'Nyeri dada atipikal, EKG normal, troponin negatif',
                'investigations_done' => 'EKG, troponin, stress test',
                'treatment_given' => 'Antiplatelet, beta blocker, statin',
                'reason_for_referral' => 'Perlu coronary angiogram',
                'special_instructions' => 'Pantang makan 6 jam sebelum procedure',
                'status' => 'approved',
                'approved_by' => 5,
                'approved_date' => '2025-01-25',
                'approval_notes' => 'Approved for diagnostic angiogram',
                'outcome' => 'Angiogram normal, medical therapy continued',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-25',
                'transportation_mode' => 'Ambulance',
                'accompanying_person' => 'Perawat jantung',
                'insurance_coverage' => true,
                'estimated_cost' => 8000000.00,
            ],
            [
                'patient_id' => 3,
                'doctor_id' => 3,
                'referral_number' => 'RFL00520250120',
                'referral_date' => '2025-01-20',
                'urgency_level' => 'normal',
                'referral_type' => 'pediatric_specialist',
                'referring_facility' => 'RS Sirama - IGD',
                'receiving_facility' => 'RSCM - Pediatric Emergency',
                'receiving_doctor' => 'Dr. Spesialis Pediatric Emergency',
                'diagnosis' => 'Febrile Seizure',
                'clinical_findings' => 'Demam 40.2°C, kejang generalisata, post-ictal',
                'investigations_done' => 'EEG, lumbar puncture, blood culture',
                'treatment_given' => 'Antipiretik, anticonvulsant, antibiotic',
                'reason_for_referral' => 'Evaluasi febrile seizure, suspect meningitis',
                'special_instructions' => 'Monitor suhu, cegah kejang berulang',
                'status' => 'completed',
                'approved_by' => 8,
                'approved_date' => '2025-01-20',
                'approval_notes' => 'Transferred for pediatric specialist care',
                'outcome' => 'Discharged after 48 hours observation',
                'follow_up_required' => true,
                'follow_up_date' => '2025-02-20',
                'transportation_mode' => 'Ambulance pediatric',
                'accompanying_person' => 'Orang tua + Perawat',
                'insurance_coverage' => true,
                'estimated_cost' => 3000000.00,
            ],
        ];

        foreach ($referrals as $referral) {
            Referral::create($referral);
        }
    }
}
